apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
  labels:
    role-type: cluster-role
    app.kubernetes.io/managed-by: user-management
  annotations:
    description: "提供在集群中的全部权限."
    author: "Platform Installer"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]