apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-viewer
  labels:
    role-type: platform-role
    app.kubernetes.io/managed-by: user-management
  annotations:
    description: "提供在平台中的资源查看权限."
    author: "Platform Installer"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]