# permissions for end users to view users.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: user-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: user-management
    app.kubernetes.io/part-of: user-management
    app.kubernetes.io/managed-by: kustomize
  name: user-viewer-role
rules:
- apiGroups:
  - users.openfuyao.com
  resources:
  - users
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - users.openfuyao.com
  resources:
  - users/status
  verbs:
  - get
