apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    openfuyao.com/clusterrole-ref: platform-admin
    openfuyao.com/user-ref: admin
    role-type: platform-role
  name: admin-platform-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openfuyao-platform-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: admin