apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openfuyao-cluster-editor
  labels:
    role-type: cluster-role
    app.kubernetes.io/managed-by: user-management
  annotations:
    description: "cluster-editor具有集群中原生k8s资源的改查权限，但是对于平台组件（例如告警、日志、监控等）仅具有查看的权限。"
    author: "Platform Installer"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
      - replicationcontrollers
      - serviceaccounts
      - events
      - namespaces
      - limitranges
      - resourcequotas
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: [""]
    resources: ["services/proxy"]
    verbs: ["get", "list"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - ingressclasses
      - networkpolicies
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["get", "list", "watch", "update", "patch"]