apiVersion: v1
kind: Service
metadata:
  name: user-management-operator
  namespace: {{ .Values.namespace.backend }}
  labels:
    app: user-management-operator
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  ports:
    - name: transport
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  publishNotReadyAddresses: true
  selector:
    app: user-management-operator
  sessionAffinity: None
  type: {{ .Values.service.type }}
