apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.backend }}
  labels:
    k8s-app: user-management-operator
    addonmanager.kubernetes.io/mode: Reconcile
